version: '3'
services:
  zookeeper:
    image: "bitnami/zookeeper:latest@sha256:9345f33e7796fefcea653b1e2ab9bc5451ad760f9df5634cea15360949105f4c"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "bitnami/kafka:latest@sha256:7850b113b37c4c8aa4a4d07fccbce7370af9461343386c08989e0a3449aee8e3"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper