apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: advent-demo-saas
build:
  local:
    push: false
  artifacts:
    - image: advent_demo_saas_api
      context: sample-saas
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
      docker:
        dockerfile: Dockerfile
    - image: advent_demo_saas_web
      context: toolkit_tut
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
