apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: advent-demo-saas_tenant
build:
  local:
    push: false
  artifacts:
    - image: tenant-api
      context: client_backend
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
      docker:
        dockerfile: Dockerfile
    - image: tenant-web
      context: client
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - infra/k8s/tenant/*
