apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-dep
spec:
  selector:
    matchLabels:
      app: kafka-dep
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: ibmcom/eventstreams-kafka-ce
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 7070
          readinessProbe:
            httpGet:
              port: 7070
              path: "/readiness"
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: "/liveness"
              port: 7070
            initialDelaySeconds: 360
            failureThreshold: 3
            periodSeconds: 15
